#ifdef _WIN32_WCE
#define SS_PATHELLIPSIS                 0
#endif
#define IDC_STATIC                      -1
#define IDB_TYPES                       105
#define IDB_ARROWUP                     108
#define IDB_ARROWDOWN                   109
#define IDC_APPLY                       1000
#define IDC_EDITSTR                     1002
#define IDC_HEXNUM                      1002
#define IDC_EDIT_SERACH                 1002
#define IDC_KEYTO                       1002
#define IDC_E_FILENAME                  1002
#define IDC_E_FILENAME2                 1003
#define IDC_VNAME                       1004
#define IDC_SLIST                       1005
#define IDC_L_NAMES                     1005
#define IDC_E_COMMENT                   1005
#define IDC_DECNUM                      1006
#define IDC_STARTKEY                    1006
#define IDC_KEYFROM                     1006
#define IDC_E_COMP                      1006
#define IDC_VSLIST                      1007
#define IDC_OLDNAME                     1007
#define IDC_EDIT_STARTVAL               1007
#define IDC_BUTTON1                     1008
#define IDC_MOVEDOWN                    1008
#define IDC_BUTTON_BROWSE               1008
#define IDC_B_ALL                       1008
#define IDC_BROWSECOMP                  1008
#define IDC_MOVEUP                      1009
#define IDC_NEWNAME                     1009
#define IDC_BUTTON_SELTYPE              1009
#define IDC_NEW                         1010
#define IDC_OLDDATA                     1010
#define IDC_DEL                         1011
#define IDC_NEWDATA                     1011
#define IDC_CONCAT                      1012
#define IDC_TYPEID                      1013
#define IDC_HEXEDIT                     1016
#define IDC_RESULTNUM                   1017
#define IDC_EDIT_REPLACE                1018
#define IDC_CASE                        1021
#define IDC_NOCHNG                      1022
#define IDC_EDIT_LOGFNAME               1023
#define IDC_EDIT3                       1024
#define IDC_ENDKEY                      1024
#define IDC_KEYNAME                     1025
#define IDPAUSE                         1026
#define IDC_B_SKIP                      1027
#define IDC_ST_NEWNAME                  1028
#define IDC_ST_NEWDATA                  1029
#define IDC_C_HKLM                      1030
#define IDC_C_HKCR                      1031
#define IDC_C_HKUS                      1032
#define IDC_C_HKPD                      1033
#define IDC_C_HKDD                      1034
#define IDC_B_CHOOSE                    1035
#define IDC_E_KEYNAME                   1036
#define IDC_B_GETPRIV                   1037
#define IDC_E_KEYTITLE                  1037
#define IDC_SEWARN                      1038
#define IDC_E_SUBKEYNAME                1039
#define IDC_B_CHOOSE2                   1039
#define IDC_CHK_FORCE                   1040
#define IDC_CHK_NOLAZY                  1041
#define IDC_CHK_REFRESH                 1042
#define IDC_CHK_HIVEVOL                 1043
#define IDC_VALNAMES                    1044
#define IDC_VALDATA                     1045
#define IDC_KEYNAMES                    1046
#define IDC_STATIC_REPLACE              1047
#define IDC_ALPHORD                     1048
#define IDC_S_STARTKEY                  1049
#define IDC_S_ENDKEY                    1050
#define IDC_C_MOVE                      1051
#define IDC_S_STARTVAL                  1051
#define IDC_C_ALLOWCRIT                 1054
#define IDC_C_SAVESETTINGS              1055
#define IDC_C_ENRRKMENU                 1056
#define IDC_C_SHOWSTARTVAL              1058
#define IDC_C_SHOWSTRTYPE               1059
#define IDC_C_0                         1060
#define IDC_C_1                         1061
#define IDC_B_CALL_BE_SRCH              1061
#define IDC_C_2                         1062
#define IDC_B_CALL_BE_RPL               1062
#define IDC_C_3                         1063
#define IDC_C_CESC_SRCH                 1063
#define IDC_C_4                         1064
#define IDC_C_CESC_RPL                  1064
#define IDC_C_5                         1065
#define IDC_C_USEVAL                    1065
#define IDC_C_6                         1066
#define IDC_C_USECOMM                   1066
#define IDC_C_7                         1067
#define IDC_C_8                         1068
#define IDC_C_9                         1069
#define IDC_C_10                        1070
#define IDC_C_11                        1071
#define IDM_EXIT                        40001
#define IDM_SETTINGS                    40002
#define IDM_ABOUT                       40003
#define IDM_DEBUG_MOVE                  40004
#define IDM_DEBUG_COPY                  40005
#define IDM_SEARCHREPLACE               40006
#define IDM_IMPORTREGFILE               40007
#define IDM_EXPORTREGFILE               40008
#define IDM_REGISTRY_CONNECT            40009
#define IDM_REGISTRY_DISCONNECT         40010
#define ID_EDIT_SAVEKEYTOFILE           40012
#define ID_EDIT_LOADKEYFROMFILE         40013
#define IDM_FINDNEXT                    40014
#define ID_REGISTRY_LOADHIVE            40015
#define IDM_REGISTRY_LOADHIVE           40015
#define ID_REGISTRY_UNLOADHIVE          40016
#define IDM_REGISTRY_UNLOADHIVE         40016
#define ID_EDIT_REPLACEKEY              40018
#define IDM_FAV_GOTO                    40019
#define IDM_FAV_ADDKEY                  40021
#define IDM_FAV_EDIT                    40022
#define IDM_EDIT_FIND                   40023
#define IDM_EDIT_UNDO                   40024
